### ISSUE TITLE
template tag won't parse

### ISSUE THREAD

**Issue by derek73** [antonagestam/django-text#57]
I installed django-text into my app according to the instructions in the readme, but when I load the page the default content does not appear on the page. Instead I get a template tag and some HTML.

```
        {% text "text_body" "test text here"%}
        {% blocktext "homepage_intro" %}
        lorem ipsum
        {% endblocktext %}
```

puts this into the page

```
            &lt;span data-text-name="text_body" class="dj_text_inline_wrapper"&gt;{{ text_placeholder_text_body }}&lt;/span&gt;
            <span data-text-name="homepage_intro" class="dj_text_inline_wrapper">{{ text_placeholder_homepage_intro }}</span>
```

I do see an "Edit texts" button on the page. When I press it an admin interface pops up, and my template tags are listed. When I click one, I get a 404 error. 

```
[10/Mar/2016 16:26:33] "GET /django_text/text/text_body_en-us/ HTTP/1.1" 404 3286
```

I tried using the admin to add a piece of content with that slug, but still get a 404. Which is odd because the url does show up in show_urls.

```
 ./manage.py show_urls
...
/django_text/text/<text_slug>/  text.views.TextView django_text:text    
/django_text/update_text/<text_id>/ text.views.TextUpdateView   django_text:update_text 
...
```

Using Django 1.9.4

Any ideas what I might be doing wrong?

**Comment by antonagestam** [comment]
What does your settings look like? Specifically `MIDDLEWARE_CLASSES`. Also what version of Python are you running this on?

**Comment by derek73** [comment]
Python 2.7.11

```
MIDDLEWARE_CLASSES = (
    'domain.middleware.NoWwwMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'text.middleware.TextMiddleware',
    'text.middleware.ToolbarMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
)

TEMPLATES = [{u'BACKEND': u'django.template.backends.django.DjangoTemplates',
  u'DIRS': [],
  u'OPTIONS': {u'context_processors': [u'django.contrib.auth.context_processors.auth',
    u'django.template.context_processors.debug',
    u'django.template.context_processors.i18n',
    u'django.template.context_processors.media',
    u'django.template.context_processors.request',
    u'django.template.context_processors.static',
    u'django.template.context_processors.tz',
    u'django.contrib.messages.context_processors.messages',
    u'domain.context_processors.google_analytics'],
   u'debug': True,
   u'loaders': (u'django.template.loaders.filesystem.Loader',
    u'django.template.loaders.app_directories.Loader',
    u'django.template.loaders.eggs.Loader')}}]
```

Actually that's possibly one notable difference, using the new TEMPLATES variable, the old template variables don't exist in my settings. Also the location of the context processors has changed from the readme.

**Comment by antonagestam** [comment]
I think I've found the bug. Would you mind testing out the patch before I merge and create a new release? You can install it with:

```
$ pip install -e git+git://github.com/antonagestam/django-text.git@fix-57#egg=django-text
```

**Comment by derek73** [comment]
That seemed to fix the HTML escaping issue. This is what I get now:

```
        <span data-text-name="text_body" class="dj_text_inline_wrapper">{{ text_placeholder_text_body }}</span>
        <span data-text-name="homepage_intro" class="dj_text_inline_wrapper">{{ text_placeholder_homepage_intro }}</span>
```

**Comment by antonagestam** [comment]
Alright, so making progress at least. I'll keep trying to reproduce the problem.

**Comment by derek73** [comment]
Let me know if you need any help troubleshooting. I'm happy to throw in some breakpoints and see what's going on, but not sure where to look or what to look for. I was just going to use it for a personal project so no urgency on my end.

**Comment by antonagestam** [comment]
Yeah, I wasn't able to reproduce what you're experiencing. It kind of seems like the `TextMiddleware` isn't being run (https://github.com/antonagestam/django-text/blob/master/text/middleware.py#L51). It's supposed to fetch all text nodes from the database and render them into the template.

**Comment by derek73** [comment]
Thanks, that was helpful. My problem was because my view was not returning a `TemplateResponse` object. I was using `render_to_response()`, which returns an `HttpResponse` that does not have a `render()` method, so `TextMiddleware.process_template_response()` is never executed. 

So one requirement is that any views using this need to return a `TemplateResponse` that has a `render()` method, and not an `HttpResponse` as is done by any of the methods in the `django.shortcuts` module. Should probably add that to the docs someplace. 

So now my template tags are parsed and show up on the page as expected. I just tracked down the other remaining problem with the texts not loading in its admin and made a pull request.

**Comment by antonagestam** [comment]
Oh, that's something I had not realized. I should probably rethink using  `process_template_response`, glad you find that out!

**Comment by antonagestam** [comment]
@derek73 I just pushed a fix for this, check it out on the fix-57 branch if you want to, otherwise I'll merge it and issue a release in a few days.

**Comment by antonagestam** [comment]
Aaaand now the tests are passing too ^^.

Thanks a bunch for being so helpful with all the issues btw, glad someone's giving this project some love!

**Comment by derek73** [comment]
Just tried it out and that works for me. Thanks for the fix. And thanks for the project. Just the kind of lightweight thing I was looking for.

**Comment by antonagestam** [comment]
Just published this in a new release on PyPI
