### ISSUE TITLE
blocktext text does not update

### ISSUE THREAD

**Issue by derek73** [antonagestam/django-text#61]
I ran into one other issue that I wasn't able to solve, text inside the block text tag does not update when you save it. it appears to be an issue the medium-editor. Typing in the WYSIWYG does not change the form values submitted to the view. Text that uses the text tag works fine.

**Comment by antonagestam** [comment]
Should be fixed by 850acbed2fd12005a840a33e84c6c9862c9edb5a that I just merged to master, thanks for the heads up! :cake:
